spring:
  liquibase:
    change-log: db/changelog/changelog-master.yml
    default-schema: metadata

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/db_finance_manager
    username: db_finance_manager
    password: db_finance_manager


# http://localhost:8080/swagger-ui/index.html

